//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.06 at 07:19:09 PM EEST 
//


package ua.myService.taxi.model.driver;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.NormalizedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ua.myService.taxi.model.Entity;



/**
 * <p>Java class for Car complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Car"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://model.lb2.ua.mylaba/}Entity"&gt;
 *       &lt;all&gt;
 *         &lt;element name="brand"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="70"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="name"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&gt;
 *               &lt;minLength value="1"/&gt;
 *               &lt;maxLength value="70"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="yearOfProduction"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer"&gt;
 *               &lt;minInclusive value="1980"/&gt;
 *               &lt;maxInclusive value="2022"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="number"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="[A-Z]{2}[0-9]{4}[A-Z]{2}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="vinNumber"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;length value="17"/&gt;
 *               &lt;pattern value="[\d|A-Z]{17}"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="c_class"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Економ"/&gt;
 *               &lt;enumeration value="Середній"/&gt;
 *               &lt;enumeration value="Преміум"/&gt;
 *               &lt;enumeration value="Вантажний"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="color"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="Чорний"/&gt;
 *               &lt;enumeration value="Білий"/&gt;
 *               &lt;enumeration value="Сірий"/&gt;
 *               &lt;enumeration value="Зелений"/&gt;
 *               &lt;enumeration value="Синій"/&gt;
 *               &lt;enumeration value="Жовтий"/&gt;
 *               &lt;enumeration value="Червоний"/&gt;
 *               &lt;enumeration value="Коричневий"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Car", propOrder = {
        "brand",
        "name",
        "yearOfProduction",
        "number",
        "vinNumber",
        "cClass",
        "color"
})
public class Car
        extends Entity {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String brand;
    @XmlElement(name = "c_name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    protected int yearOfProduction;
    @XmlElement(required = true)
    protected String number;
    @XmlElement(required = true)
    protected String vinNumber;
    @XmlElement(name = "c_class", required = true, defaultValue = "\u0415\u043a\u043e\u043d\u043e\u043c")
    protected String cClass;
    @XmlElement(required = true, defaultValue = "\u0421\u0456\u0440\u0438\u0439")
    protected String color;

    /**
     * Gets the value of the brand property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBrand(String value) {
        this.brand = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the yearOfProduction property.
     */
    public int getYearOfProduction() {
        return yearOfProduction;
    }

    /**
     * Sets the value of the yearOfProduction property.
     */
    public void setYearOfProduction(int value) {
        this.yearOfProduction = value;
    }

    /**
     * Gets the value of the number property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the vinNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVinNumber() {
        return vinNumber;
    }

    /**
     * Sets the value of the vinNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVinNumber(String value) {
        this.vinNumber = value;
    }

    /**
     * Gets the value of the cClass property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCClass() {
        return cClass;
    }

    /**
     * Sets the value of the cClass property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCClass(String value) {
        this.cClass = value;
    }

    /**
     * Gets the value of the color property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setColor(String value) {
        this.color = value;
    }

    @Override
    public String toString() {
        return "Car: id = " + id + "\tcode = " + code + " {" +
                "brand='" + brand + '\'' +
                ", name='" + name + '\'' +
                ", yearOfProduction=" + yearOfProduction +
                ", number='" + number + '\'' +
                ", vinNumber='" + vinNumber + '\'' +
                ", cClass='" + cClass + '\'' +
                ", color='" + color + '\'' +
                "}";
    }

    public Car(int id, String brand, String name, int yearOfProduction, String number, String vinNumber, String cClass, String color) {
        super(id);
        this.brand = brand;
        this.name = name;
        this.yearOfProduction = yearOfProduction;
        this.number = number;
        this.vinNumber = vinNumber;
        this.cClass = cClass;
        this.color = color;
    }

    public Car() {
    }

    public Car(int id, String code, String brand, String name, int yearOfProduction, String number, String vinNumber, String cClass, String color) {
        super(id, code);
        this.brand = brand;
        this.name = name;
        this.yearOfProduction = yearOfProduction;
        this.number = number;
        this.vinNumber = vinNumber;
        this.cClass = cClass;
        this.color = color;
    }
}
