//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.06 at 07:19:09 PM EEST 
//


package ua.myService.taxi.model.driver;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ua.myService.taxi.model.Entity;


import java.math.BigDecimal;


/**
 * <p>Java class for Driver complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Driver"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://model.lb2.ua.mylaba/}Entity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;minLength value="2"/&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="surname"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *               &lt;minLength value="2"/&gt;
 *               &lt;maxLength value="50"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="age"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;totalDigits value="2"/&gt;
 *               &lt;minExclusive value="18"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="phone"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;pattern value="(\+380[\d]{9})|(0[\d]{9})"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="mark"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;fractionDigits value="3"/&gt;
 *               &lt;minInclusive value="0"/&gt;
 *               &lt;maxInclusive value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="car" type="{http://model.lb2.ua.mylaba/driver/}Car"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Driver", propOrder = {
        "name",
        "surname",
        "age",
        "phone",
        "mark",
        "car"
})
public class Driver
        extends Entity {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String name;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String surname;
    protected int age;
    @XmlElement(required = true)
    protected String phone;
    @XmlElement(required = true)
    protected BigDecimal mark;
    @XmlElement(required = true)
    protected Car car;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the surname property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the age property.
     */
    public int getAge() {
        return age;
    }

    /**
     * Sets the value of the age property.
     */
    public void setAge(int value) {
        this.age = value;
    }

    /**
     * Gets the value of the phone property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the mark property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getMark() {
        return mark;
    }

    /**
     * Sets the value of the mark property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setMark(BigDecimal value) {
        this.mark = value;
    }

    /**
     * Gets the value of the car property.
     *
     * @return possible object is
     * {@link Car }
     */
    public Car getCar() {
        return car;
    }

    /**
     * Sets the value of the car property.
     *
     * @param value allowed object is
     *              {@link Car }
     */
    public void setCar(Car value) {
        this.car = value;
    }

    @Override
    public String toString() {
        return "Driver: id = " + id + "\tcode = " + code + " {" +
                "name='" + name + '\'' +
                ", surname='" + surname + '\'' +
                ", age=" + age +
                ", phone='" + phone + '\'' +
                ", mark=" + mark +
                "\n\t\t\t" + car +
                "}\n";
    }

    public Driver(int id, String name, String surname, int age, String phone, BigDecimal mark, String carBrand, String carName, int yearOfProduction, String number, String vin, String carClass, String color) {
        super(id);
        this.car = new Car(id, carName, carBrand, yearOfProduction, number, vin, carClass, color);
        this.name = name;
        this.surname = surname;
        this.age = age;
        this.phone = phone;
        this.mark = mark;
    }

    public Driver() {
    }

    public Driver(int id, String code, String name, String surname, int age, String phone, BigDecimal mark, String carBrand, String carName, int yearOfProduction, String number, String vin, String carClass, String color) {
        super(id,code);
        this.car = new Car(id,code, carName, carBrand, yearOfProduction, number, vin, carClass, color);
        this.name = name;
        this.surname = surname;
        this.age = age;
        this.phone = phone;
        this.mark = mark;
    }

}
