//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.10.06 at 07:19:09 PM EEST 
//


package ua.myService.taxi.model.order;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import ua.myService.taxi.model.Entity;
import ua.myService.taxi.model.driver.Driver;
import ua.myService.taxi.model.user.User;

import java.math.BigDecimal;


/**
 * <p>Java class for Order complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Order"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://model.lb2.ua.mylaba/}Entity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="driver" type="{http://model.lb2.ua.mylaba/driver/}Driver"/&gt;
 *         &lt;element name="user" type="{http://model.lb2.ua.mylaba/user/}User"/&gt;
 *         &lt;element name="price"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal"&gt;
 *               &lt;fractionDigits value="2"/&gt;
 *               &lt;minInclusive value="0"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="mark"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int"&gt;
 *               &lt;minInclusive value="1"/&gt;
 *               &lt;maxInclusive value="10"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Order", propOrder = {
        "driver",
        "user",
        "price",
        "mark"
})
public class Order
        extends Entity {

    @XmlElement(required = true)
    protected Driver driver;
    @XmlElement(required = true)
    protected User user;
    @XmlElement(required = true)
    protected BigDecimal price;
    protected int mark;

    /**
     * Gets the value of the driver property.
     *
     * @return possible object is
     * {@link Driver }
     */
    public Driver getDriver() {
        return driver;
    }

    /**
     * Sets the value of the driver property.
     *
     * @param value allowed object is
     *              {@link Driver }
     */
    public void setDriver(Driver value) {
        this.driver = value;
    }

    /**
     * Gets the value of the user property.
     *
     * @return possible object is
     * {@link User }
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     *
     * @param value allowed object is
     *              {@link User }
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the price property.
     *
     * @return possible object is
     * {@link BigDecimal }
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     *
     * @param value allowed object is
     *              {@link BigDecimal }
     */
    public void setPrice(BigDecimal value) {
        this.price = value;
    }

    /**
     * Gets the value of the mark property.
     */
    public int getMark() {
        return mark;
    }

    /**
     * Sets the value of the mark property.
     */
    public void setMark(int value) {
        this.mark = value;
    }

    @Override
    public String toString() {
        return "Order id = " + id + "\tcode = " + code + "\n\t{\n" +
                "\t\t" + driver +
                "\n\t\tUser: " + user +
                "\n\tprice = " + price +
                "\n\tmark = " + mark +
                "\n\t}\n===============================";
    }

    public Order(int id, Driver driver, User user, BigDecimal price, int mark) {
        super(id);
        this.driver = driver;
        this.user = user;
        this.price = price;
        this.mark = mark;
    }

    public Order() {
    }

    public Order(int id, String code,Driver driver, User user, BigDecimal price, int mark) {
        super(id,code);
        this.driver = driver;
        this.user = user;
        this.price = price;
        this.mark = mark;
    }

}
